import { toActionsTypes } from 'cfx.redux-types'

export default toActionsTypes {

  # SAGAS
  'USER_REFRESH_TOKEN'
  'USER_SIGNUP'
  'USER_LOGIN'
  'USER_FETCH'
  'USER_FETCH_ALL'
  'USER_VER_EMAIL'
  'USER_RESET_PSD_WITH_EMAIL'
  'USER_RESET_PSD'
  'USER_RESET_SESSIONTOKEN'
  'USER_UPDATE'
  'USER_DELETE'

  # REDUCE
  'USER_SAVE'
  'USER_PATCH'
  'USER_RELOAD'
  'USER_REMOVE'
  'USER_REMOVE_ALL'
  
}