import { toActionsTypes } from 'cfx.redux-types'

export default toActionsTypes {

  # TODO SAGAS
  'TODO_CREATE'
  'TODO_UPDATE'
  'TODO_DELETE'
  'TODO_DELETE_ALL'
  'TODO_FETCH'
  'TODO_FETCH_ALL'

  # TODO REDUCE
  'TODO_SAVE'
  'TODO_PATCH'
  'TODO_RELOAD'
  'TODO_REMOVE'
  'TODO_REMOVE_ALL'

  # USER SAGAS
  'USER_REFRESH_TOKEN'
  'USER_SIGNUP'
  'USER_LOGIN'
  'USER_FETCH'
  'USER_FETCH_ALL'
  'USER_VER_EMAIL'
  'USER_RESET_PSD_WITH_EMAIL'
  'USER_RESET_PSD'
  'USER_RESET_SESSIONTOKEN'
  'USER_UPDATE'
  'USER_DELETE'

  # USER REDUCE
  'USER_SAVE'  
  'USER_PATCH'
  'USER_RELOAD'
  'USER_REMOVE'
  'USER_REMOVE_ALL'

}